

services:
  nginx:
    image: nginx:latest
    container_name: nginx-test
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app

  flask-app:
    image: python:3.9
    container_name: flask-app
    volumes:
      - ./src/python:/app
    working_dir: /app
    command: bash -c "pip install flask && python main.py"

